"""
Exit Order Data Model - Campaign Exit Management System

Purpose:
--------
Provides Pydantic model for tracking triggered exit orders within campaigns.
Each exit order represents a partial exit (target hit), stop loss trigger,
or emergency invalidation exit.

Data Model:
-----------
ExitOrder: Individual exit order with tracking of trigger conditions and execution status

Integration:
------------
- Story 9.5: Campaign exit management with partial exits and invalidation
- Story 9.4: Links to positions via position_id FK
- Story 9.1: Links to campaigns via campaign_id FK

Author: Story 9.5
"""

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID, uuid4

from pydantic import BaseModel, ConfigDict, Field, field_validator, model_serializer


class ExitOrder(BaseModel):
    """
    Triggered exit order for a campaign position.

    Represents a triggered exit condition (partial exit at target, stop loss
    triggered, or emergency invalidation exit). Exit orders are generated by
    the CampaignExitManager and tracked until executed by the broker.

    Order Types:
    ------------
    - PARTIAL_EXIT: Target level hit (T1, T2, or T3)
    - STOP_LOSS: Stop loss price triggered
    - INVALIDATION: Emergency exit due to campaign invalidation

    Fields:
    -------
    - id: Unique exit order identifier (UUID)
    - campaign_id: Parent campaign (FK to campaigns.id)
    - position_id: Source position (FK to positions.id)
    - order_type: PARTIAL_EXIT | STOP_LOSS | INVALIDATION
    - exit_level: Price at which exit triggered (NUMERIC(18,8))
    - shares: Number of shares to exit
    - reason: Human-readable explanation (e.g., "T1 target hit at $160.00")
    - triggered_at: Timestamp when exit condition detected (UTC)
    - executed: Boolean flag for broker execution tracking

    Constraints:
    ------------
    - All price fields use Decimal type (NEVER float) for precision
    - All datetime fields enforce UTC timezone via validator
    - shares must be positive integer (> 0)
    - Foreign keys: campaign_id, position_id (both ON DELETE RESTRICT)

    Example:
    --------
    >>> from decimal import Decimal
    >>> from datetime import datetime, UTC
    >>> from uuid import uuid4
    >>> exit_order = ExitOrder(
    ...     campaign_id=uuid4(),
    ...     position_id=uuid4(),
    ...     order_type="PARTIAL_EXIT",
    ...     exit_level=Decimal("160.00"),
    ...     shares=50,
    ...     reason="T1 target hit at $160.00",
    ...     triggered_at=datetime.now(UTC),
    ...     executed=False
    ... )
    """

    # Core identification
    id: UUID = Field(default_factory=uuid4, description="Unique exit order identifier")
    campaign_id: UUID = Field(..., description="Parent campaign (FK to campaigns.id)")
    position_id: UUID = Field(..., description="Source position (FK to positions.id)")

    # Exit details
    order_type: str = Field(
        ...,
        max_length=20,
        description="PARTIAL_EXIT | STOP_LOSS | INVALIDATION",
    )
    exit_level: Decimal = Field(
        ...,
        decimal_places=8,
        max_digits=18,
        gt=Decimal("0"),
        description="Price at which exit triggered",
    )
    shares: int = Field(..., gt=0, description="Number of shares to exit")
    reason: str = Field(..., description="Human-readable explanation of exit trigger")

    # Timestamps
    triggered_at: datetime = Field(..., description="Timestamp when exit condition detected (UTC)")

    # Execution tracking
    executed: bool = Field(default=False, description="Boolean flag for broker execution tracking")

    # Record timestamps
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(UTC), description="Record creation timestamp"
    )

    model_config = ConfigDict(
        json_encoders={Decimal: str, datetime: lambda v: v.isoformat()},
    )

    @field_validator("order_type")
    @classmethod
    def validate_order_type(cls, v: str) -> str:
        """
        Validate order type is valid exit type.

        Valid exit types: PARTIAL_EXIT, STOP_LOSS, INVALIDATION

        Parameters:
        -----------
        v : str
            Order type to validate

        Returns:
        --------
        str
            Validated order type (uppercase)

        Raises:
        -------
        ValueError
            If order_type is invalid
        """
        valid_types = {"PARTIAL_EXIT", "STOP_LOSS", "INVALIDATION"}
        v_upper = v.upper()
        if v_upper not in valid_types:
            raise ValueError(f"Invalid order type: {v}. Valid exit types: {', '.join(valid_types)}")
        return v_upper

    @field_validator("triggered_at", "created_at", mode="before")
    @classmethod
    def ensure_utc(cls, v: datetime | str | None) -> datetime | None:
        """
        Enforce UTC timezone on all datetime fields.

        Critical for accurate timestamp handling across timezones and preventing
        timezone-related bugs in exit order tracking and audit trails.

        Parameters:
        -----------
        v : datetime | str | None
            Datetime value to validate

        Returns:
        --------
        datetime | None
            UTC-aware datetime or None

        Raises:
        -------
        ValueError
            If datetime cannot be parsed or converted to UTC
        """
        if v is None:
            return None

        # Handle string timestamps (from JSON deserialization)
        if isinstance(v, str):
            parsed = datetime.fromisoformat(v.replace("Z", "+00:00"))
            return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)

        # Handle datetime objects
        if v.tzinfo is None:
            return v.replace(tzinfo=UTC)
        return v.astimezone(UTC)

    @model_serializer
    def serialize_model(self) -> dict[str, Any]:
        """
        Serialize model with Decimal as strings and UUID as strings.

        Preserves decimal precision in JSON by serializing as strings,
        avoiding floating-point precision loss.

        Returns:
        --------
        dict[str, Any]
            Serialized model data
        """
        return {
            "id": str(self.id),
            "campaign_id": str(self.campaign_id),
            "position_id": str(self.position_id),
            "order_type": self.order_type,
            "exit_level": str(self.exit_level),
            "shares": self.shares,
            "reason": self.reason,
            "triggered_at": self.triggered_at.isoformat(),
            "executed": self.executed,
            "created_at": self.created_at.isoformat(),
        }
