"""
Daily Summary Data Models (Story 10.3)

Purpose:
--------
Provides Pydantic models for the daily summary response, showing overnight
trading activity including symbols scanned, patterns detected, signals
executed/rejected, portfolio heat changes, and suggested actions.

Data Models:
------------
- DailySummary: Complete daily summary response

Features:
---------
- Fixed-point arithmetic: Decimal type for portfolio_heat_change
- UTC timestamps: Enforced on all datetime fields
- Serialization: Custom @field_serializer for Decimal → str, datetime → ISO format (Pydantic V2)

Author: Story 10.3
"""

from datetime import UTC, datetime
from decimal import Decimal
from typing import Any

from pydantic import BaseModel, Field, field_serializer, field_validator


class DailySummary(BaseModel):
    """
    Daily summary of trading activity (Story 10.3, AC: 3, 4).

    Contains aggregated metrics from the last 24 hours and business logic
    generated action items for trader review.

    Fields:
    -------
    - symbols_scanned: Total unique symbols analyzed in last 24 hours
    - patterns_detected: Total patterns detected (all types)
    - signals_executed: Count of signals with status EXECUTED
    - signals_rejected: Count of signals with rejection_reason not null
    - portfolio_heat_change: Change in portfolio heat % over 24 hours (Decimal)
    - suggested_actions: Array of action strings from business logic
    - timestamp: When summary was generated (UTC)

    Example:
    --------
    >>> from decimal import Decimal
    >>> from datetime import datetime, UTC
    >>> summary = DailySummary(
    ...     symbols_scanned=15,
    ...     patterns_detected=23,
    ...     signals_executed=4,
    ...     signals_rejected=8,
    ...     portfolio_heat_change=Decimal("1.2"),
    ...     suggested_actions=[
    ...         "Review Campaign C-2024-03-15-AAPL: 2 positions approaching stops",
    ...         "Portfolio heat at 7.8% - capacity for ~2 more signals"
    ...     ],
    ...     timestamp=datetime.now(UTC)
    ... )
    """

    symbols_scanned: int = Field(
        ..., ge=0, description="Total unique symbols analyzed in last 24 hours"
    )

    patterns_detected: int = Field(..., ge=0, description="Total patterns detected (all types)")

    signals_executed: int = Field(..., ge=0, description="Count of signals with status EXECUTED")

    signals_rejected: int = Field(
        ..., ge=0, description="Count of signals with rejection_reason not null"
    )

    portfolio_heat_change: Decimal = Field(
        ...,
        decimal_places=4,
        max_digits=8,
        description="Change in portfolio heat % over 24 hours",
    )

    suggested_actions: list[str] = Field(
        default_factory=list, description="Action strings generated by business logic"
    )

    timestamp: datetime = Field(..., description="When summary was generated (UTC)")

    @field_validator("timestamp", mode="before")
    @classmethod
    def ensure_utc(cls, v: datetime | str) -> datetime:
        """Enforce UTC timezone on timestamp."""
        # Handle string timestamps (from JSON deserialization)
        if isinstance(v, str):
            from datetime import datetime as dt

            parsed = dt.fromisoformat(v.replace("Z", "+00:00"))
            return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)

        # Handle datetime objects
        if v.tzinfo is None:
            return v.replace(tzinfo=UTC)
        return v.astimezone(UTC)

    @field_serializer("portfolio_heat_change", when_used="json")
    def serialize_decimal(self, value: Decimal, _info: Any) -> str:
        """Serialize Decimal to string for JSON compatibility (Pydantic V2)."""
        return str(value)

    @field_serializer("timestamp", when_used="json")
    def serialize_timestamp(self, value: datetime, _info: Any) -> str:
        """Serialize datetime to ISO format string (Pydantic V2)."""
        return value.isoformat()

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "symbols_scanned": 15,
                    "patterns_detected": 23,
                    "signals_executed": 4,
                    "signals_rejected": 8,
                    "portfolio_heat_change": "1.2",
                    "suggested_actions": [
                        "Review Campaign C-2024-03-15-AAPL: 2 positions approaching stops",
                        "Portfolio heat at 7.8% - capacity for ~2 more signals",
                    ],
                    "timestamp": "2024-03-15T14:30:00Z",
                }
            ]
        },
    }
