name: 'Setup Python Backend'
description: 'Install Python, Poetry, and backend dependencies with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  poetry-version:
    description: 'Poetry version to install'
    required: false
    default: '1.7.1'
  working-directory:
    description: 'Working directory for backend'
    required: false
    default: 'backend'

runs:
  using: 'composite'
  steps:
    - name: Setup Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.working-directory }}/.venv
          ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles(format('{0}/poetry.lock', inputs.working-directory)) }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: poetry install --with dev
