"""
Exit Strategy Base Classes - Story 18.11.1

Purpose:
--------
Defines abstract base class for exit strategies and supporting data structures.
Provides pluggable exit logic framework for backtesting engine.

Classes:
--------
- ExitContext: Context data for exit strategy evaluation
- ExitSignal: Exit signal with reason and price
- ExitStrategy: Abstract base class for all exit strategies

Author: Story 18.11.1
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal
from typing import Optional

from src.models.ohlcv import OHLCVBar
from src.models.position import Position


@dataclass
class ExitContext:
    """
    Context data provided to exit strategies for decision making.

    Contains all information needed to evaluate exit conditions including
    current market state, position details, and dynamic exit levels.

    Attributes:
    -----------
    trailing_stop : Decimal
        Current trailing stop price
    target_price : Decimal | None
        Optional profit target price
    entry_time : datetime
        Position entry timestamp
    max_hold_bars : int
        Maximum number of bars to hold position
    bars_held : int
        Number of bars position has been held
    campaign_phase : str | None
        Current Wyckoff phase of campaign (if applicable)
    """

    trailing_stop: Decimal
    target_price: Optional[Decimal] = None
    entry_time: datetime = None
    max_hold_bars: int = 100
    bars_held: int = 0
    campaign_phase: Optional[str] = None


@dataclass
class ExitSignal:
    """
    Exit signal generated by exit strategy.

    Represents a decision to exit a position with the reason
    and execution price.

    Attributes:
    -----------
    reason : str
        Exit reason (e.g., "trailing_stop", "target_hit", "time_exit")
    price : Decimal
        Exit execution price
    timestamp : datetime | None
        Optional timestamp of exit signal
    """

    reason: str
    price: Decimal
    timestamp: Optional[datetime] = None


class ExitStrategy(ABC):
    """
    Abstract base class for exit strategies.

    All exit strategies must implement this interface to be compatible
    with the backtesting engine's exit logic system.

    Subclasses must implement:
    - name property: Strategy identifier for logging
    - should_exit: Exit evaluation logic

    Example:
    --------
    >>> class CustomExitStrategy(ExitStrategy):
    ...     @property
    ...     def name(self) -> str:
    ...         return "custom_exit"
    ...
    ...     def should_exit(
    ...         self, position: Position, bar: OHLCVBar, context: ExitContext
    ...     ) -> Optional[ExitSignal]:
    ...         if bar.close >= context.target_price:
    ...             return ExitSignal(reason="custom_target", price=context.target_price)
    ...         return None
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """
        Strategy name for logging and identification.

        Returns:
        --------
        str
            Unique strategy identifier (e.g., "trailing_stop", "target_exit")
        """
        pass

    @abstractmethod
    def should_exit(
        self,
        position: Position,
        bar: OHLCVBar,
        context: ExitContext,
    ) -> Optional[ExitSignal]:
        """
        Determine if position should exit based on current bar and context.

        Parameters:
        -----------
        position : Position
            Current position to evaluate
        bar : OHLCVBar
            Current price bar
        context : ExitContext
            Exit context with trailing stops, targets, timing data

        Returns:
        --------
        ExitSignal | None
            Exit signal if exit condition met, None otherwise

        Example:
        --------
        >>> signal = strategy.should_exit(position, bar, context)
        >>> if signal:
        ...     print(f"Exit triggered: {signal.reason} at ${signal.price}")
        """
        pass
