/**
 * Daily Summary Type Definitions (Story 10.3)
 *
 * TypeScript interfaces for daily trading activity summary data.
 * Auto-generated from backend Pydantic models via pydantic-to-typescript.
 *
 * NOTE: In production, this file would be auto-generated. For MVP, manually typed.
 */

import type Big from 'big.js'

/**
 * Daily Summary Response (Story 10.3, AC: 3, 4, 6)
 *
 * Contains aggregated metrics from the last 24 hours including symbols scanned,
 * patterns detected, signals executed/rejected, portfolio heat changes, and
 * suggested actions generated by business logic.
 */
export interface DailySummary {
  /** Total unique symbols with OHLCV data in last 24 hours */
  symbols_scanned: number

  /** Total enabled symbols in scanner watchlist */
  symbols_in_watchlist: number

  /** Total patterns detected (all types) */
  patterns_detected: number

  /** Count of signals with status EXECUTED */
  signals_executed: number

  /** Count of signals with rejection_reason not null */
  signals_rejected: number

  /**
   * Change in portfolio heat % over 24 hours
   * Uses Big.js for decimal precision (converted from backend Decimal)
   */
  portfolio_heat_change: Big | string

  /** Action strings generated by business logic */
  suggested_actions: string[]

  /** When summary was generated (UTC ISO 8601 string) */
  timestamp: string
}

/**
 * Dismissal State for localStorage
 *
 * Tracks when user last dismissed the daily summary card.
 * Stored in localStorage with key: 'daily_summary_last_viewed'
 */
export interface DailySummaryDismissalState {
  /** ISO date string (YYYY-MM-DD) when card was last dismissed */
  last_viewed_date: string
}
